# Generated by Django 4.2.7 on 2024-10-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('chroma_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
